INF QcomPkg/XBLCore/XBLCore.inf
INF MdeModulePkg/Core/Dxe/DxeMain.inf
INF MsSurfaceQcPkg/FirmwareBootPerformanceDxe/FirmwareBootPerformanceDxe.inf
INF MdeModulePkg/Universal/PrintDxe/PrintDxe.inf
INF MdeModulePkg/Universal/PCD/Dxe/Pcd.inf
INF QcomPkg/Drivers/EnvDxe/EnvDxeEnhanced.inf
INF MdeModulePkg/Universal/ReportStatusCodeRouter/RuntimeDxe/ReportStatusCodeRouterRuntimeDxe.inf
INF MdeModulePkg/Universal/StatusCodeHandler/RuntimeDxe/StatusCodeHandlerRuntimeDxe.inf
INF MsWheaPkg/MsWheaReport/Dxe/MsWheaReportDxe.inf
INF MdeModulePkg/Core/RuntimeDxe/RuntimeDxe.inf
INF ArmPkg/Drivers/CpuDxe/CpuDxe.inf
INF ArmPkg/Drivers/ArmGic/ArmGicDxe.inf
INF EmbeddedPkg/MetronomeDxe/MetronomeDxe.inf
INF ArmPkg/Drivers/TimerDxe/TimerDxe.inf
INF QcomPkg/Drivers/SmemDxe/SmemDxe.inf
INF QcomPkg/Drivers/DALSYSDxe/DALSYSDxe.inf
INF QcomPkg/Drivers/HWIODxe/HWIODxe.inf
INF QcomPkg/Drivers/ChipInfoDxe/ChipInfoDxe.inf
INF QcomPkg/Drivers/PlatformInfoDxe/PlatformInfoDxe.inf
INF QcomPkg/Drivers/ULogDxe/ULogDxe.inf
INF QcomPkg/Drivers/IPCCDxe/IPCCDxe.inf
INF QcomPkg/Drivers/Smp2pDxe/Smp2pDxe.inf
INF QcomPkg/Drivers/SSRDxe/SSRDxe.inf
INF QcomPkg/Drivers/GLinkDxe/GLinkDxe.inf
INF QcomPkg/Drivers/CmdDbDxe/CmdDbDxe.inf
INF QcomPkg/Drivers/PwrUtilsDxe/PwrUtilsDxe.inf
INF QcomPkg/Drivers/NpaDxe/NpaDxe.inf
INF QcomPkg/Drivers/RpmhDxe/RpmhDxe.inf
INF QcomPkg/Drivers/ShmBridgeDxe/ShmBridgeDxe.inf
INF QcomPkg/Drivers/TzDxe/ScmDxe.inf
INF QcomPkg/Drivers/MailboxDxe/MailboxDxe.inf
INF QcomPkg/Drivers/QPPCDxe/QPPCDxe.inf
INF QcomPkg/Drivers/VcsDxe/VcsDxe.inf
INF QcomPkg/Drivers/ClockDxe/ClockDxe.inf
INF QcomPkg/Drivers/ICBDxe/ICBDxe.inf
INF QcomPkg/Drivers/HALIOMMUDxe/HALIOMMUDxe.inf
INF QcomPkg/Drivers/HALIOMMUv3Dxe/HALIOMMUv3Dxe.inf
INF QcomPkg/Drivers/TLMMDxe/TLMMDxe.inf
INF MsSurfaceCorePkg/MsPcbaTestModeInfo/MsPcbaTestModeInfoDxe.inf
INF QcomPkg/Drivers/I2CDxe/I2CDxe.inf
INF QcomPkg/Drivers/SPMIDxe/SPMIDxe.inf
INF QcomPkg/Drivers/PmicDxe/PmicDxeWp.inf
INF MdeModulePkg/Universal/Disk/DiskIoDxe/DiskIoDxe.inf
INF Sc8380xpFamilyPkg/Override/MdeModulePkg/Universal/Disk/PartitionDxe/PartitionDxe.inf
INF MdeModulePkg/Universal/Disk/UnicodeCollation/EnglishDxe/EnglishDxe.inf
INF MdeModulePkg/Universal/FvSimpleFileSystemDxe/FvSimpleFileSystemDxe.inf
INF QcomPkg/Drivers/SdccDxe/SdccDxe_EntpMgmt.inf
INF QcomPkg/Drivers/SpiNorDxe/SpiNorDxe.inf
INF FatPkg/EnhancedFatDxe/Fat.inf
INF QcomPkg/Drivers/TzDxe/TzDxe.inf
INF MdeModulePkg/Bus/Pci/PciBusDxe/PciBusDxe.inf
INF QcomPkg/Drivers/VariableDxe/VariableDxe.inf
INF DenaliPkg/PlatformEntMgtPolicyDxe/PlatformEntMgtPolicyDxe.inf
INF QcomPkg/Drivers/EnterpriseMgtDxe/EnterpriseMgtDxe.inf
INF QcomPkg/Drivers/MfgModeMgmtDxe/MfgModeMgmtDxe.inf
INF QcomPkg/Drivers/QcomWDogDxe/QcomWDogDxe.inf
INF MsSurfaceQcPkg/MsEnvDxe/MsEnvDxe.inf
INF QcomPkg/Drivers/DDRInfoDxe/DDRInfoDxe.inf
INF MdeModulePkg/Universal/ResetSystemRuntimeDxe/ResetSystemRuntimeDxe.inf
INF DenaliPkg/PlatformMteSsdInitDxe/PlatformMteSsdInit.inf
INF MsSurfaceCorePkg/MuBuiltInVarPolicyInstallerDxe/MuBuiltInVarPolicyInstallerDxe.inf
INF MsSurfaceQcPkg/Override/MsCorePkg/MuVarPolicyFoundationDxe/MuVarPolicyFoundationDxe.inf
INF QcomPkg/Drivers/FvUtilsDxe/FvUtilsEnhancedDxe.inf
INF QcomPkg/Drivers/PILProxyDxe/PILProxyDxe.inf
INF QcomPkg/Drivers/PILDxe/PILDxe.inf
INF QcomPkg/Drivers/PmicGlinkDxe/PmicGlinkDxeWP.inf
INF MdeModulePkg/Universal/WatchdogTimerDxe/WatchdogTimer.inf
INF BaseCryptoDriverDxeAARCH64/BaseCryptoDriverDxeAARCH64.inf
INF MdeModulePkg/Universal/SecurityStubDxe/SecurityStubDxe.inf
INF QcomPkg/Drivers/SecurityDxe/SecurityDxe.inf
INF QcomPkg/Drivers/RawFileSystemDxe/RawFileSystemDxe.inf
INF QcomPkg/Drivers/RawFsSimpleFsDxe/RawFsSimpleFsDxe.inf
INF QcomPkg/Drivers/PASRDxe/PASRDxe.inf
INF QcomPkg/Drivers/GpiDxe/GpiDxe.inf
INF QcomPkg/Drivers/QcomScmiDxe/QcomScmiDxe.inf
INF QcomPkg/Drivers/CalibrationDxe/CalibrationDxe.inf
INF Sc8380xpFamilyPkg/SurfaceSocDebugDxe/SurfaceSocDebugDxe.inf
INF QcomPkg/Drivers/QcomChargerDxe/QcomChargerDxeWp.inf
INF QcomPkg/Drivers/RemapDxe/RemapDxe.inf
INF QcomPkg/Drivers/ChargerExDxe/ChargerExDxeWP.inf
INF QcomPkg/Drivers/NvmePowerControlDxe/NvmePowerControlDxe.inf
INF QcomPkg/Drivers/NvmeMemCardDxe/NvmeMemCardDxe.inf
INF QcomPkg/Drivers/SPSSDxe/SPSSDxe.inf
INF QcomPkg/Drivers/DppDxe/DppDxe.inf
INF EmbeddedPkg/RealTimeClockRuntimeDxe/RealTimeClockRuntimeDxe.inf
INF MdeModulePkg/Universal/DevicePathDxe/DevicePathDxe.inf
INF MdeModulePkg/Universal/HiiDatabaseDxe/HiiDatabaseDxe.inf
INF MdeModulePkg/Universal/BdsDxe/BdsDxe.inf
INF QcomPkg/Drivers/SPIDxe/SPIDxe.inf
INF QcomPkg/Drivers/HSUartDxe/HSUartDxe.inf
INF MsSamSupportPkg/UspTransport/Dxe/UspTransportDxe.inf
INF MsSurfaceCorePkg/MsTdmBoardIdInfo/MsTdmBoardIdInfoDxe.inf
INF QcomPkg/Drivers/WlanDxe/WlanDxe.inf
INF QcomPkg/Drivers/WwanDxe/WwanDxe.inf
INF QcomPkg/Drivers/DisplayDxe/DisplayDxe.inf
INF QcomPkg/Drivers/TsensDxe/TsensDxe.inf
INF QcomPkg/Drivers/CPRDxe/CPRDxe.inf
INF MdeModulePkg/Universal/SmbiosDxe/SmbiosDxe.inf
INF MdeModulePkg/Universal/Acpi/AcpiTableDxe/AcpiTableDxe.inf
INF Sc8380xpFamilyPkg/Override/QcomPkg/Drivers/AcpiPlatformDxe/AcpiPlatformDxe.inf
INF QcomPkg/Drivers/WinAcpiUpdate/WinAcpiUpdate.inf
INF QcomPkg/Drivers/UCDxe/UCDxe.inf
INF QcomPkg/Drivers/RNGDxe/RngDxe.inf
INF QcomPkg/Drivers/RscDxe/RscDxe.inf
INF QcomPkg/Drivers/PciHostBridgeDxe/PciHostBridgeDxe.inf
INF QcomPkg/Drivers/UsbPwrCtrlDxe/UsbPwrCtrlDxeWP.inf
INF QcomPkg/Drivers/UsbfnDwc3Dxe/UsbfnDwc3Dxe.inf
INF QcomPkg/Drivers/XhciPciEmulationDxe/XhciPciEmulationDxe.inf
INF QcomPkg/Drivers/XhciDxe/XhciDxe.inf
INF QcomPkg/Drivers/UsbBusDxe/UsbBusDxe.inf
INF QcomPkg/Drivers/UsbKbDxe/UsbKbDxe.inf
INF QcomPkg/Drivers/UsbMassStorageDxe/UsbMassStorageDxe.inf
INF QcomPkg/Drivers/UsbMsdDxe/UsbMsdDxe.inf
INF QcomPkg/Drivers/UsbDeviceDxe/UsbDeviceDxe.inf
INF QcomPkg/Drivers/UsbConfigDxe/UsbConfigDxe.inf
INF QcomPkg/Drivers/UsbInitDxe/UsbInitDxe.inf
INF MsSurfaceQcPkg/VariablePolicyControlDxe/VariablePolicyControlDxe.inf
INF QcomPkg/Drivers/SmBiosTableDxe/SmBiosTableDxe.inf
INF QcomPkg/Drivers/SimpleTextInOutSerialDxe/SimpleTextInOutSerial.inf
INF MdeModulePkg/Universal/Console/ConPlatformDxe/ConPlatformDxe.inf
INF MdeModulePkg/Universal/Console/ConSplitterDxe/ConSplitterDxe.inf
INF MdeModulePkg/Universal/Console/GraphicsConsoleDxe/GraphicsConsoleDxe.inf
INF QcomPkg/Drivers/SecRSADxe/SecRSADxe.inf
INF MdeModulePkg/Bus/Pci/NvmExpressDxe/NvmExpressDxe.inf
INF MdeModulePkg/Universal/CapsuleRuntimeDxe/CapsuleRuntimeDxe.inf
INF QcomPkg/Drivers/SpcomDxe/SpcomDxe.inf
INF QcomPkg/Drivers/SpNvmDxe/SpNvmDxe.inf
INF MsGraphicsPkg/MsUiTheme/Dxe/MsUiThemeProtocol.inf
INF QcomPkg/Drivers/TrEEDxe/TpmDxe.inf
INF SecurityPkg/Tcg/Tcg2Dxe/Tcg2Dxe.inf
INF QcomPkg/Drivers/MeasurePreUefiFwDxe/MeasurePreUefiFwDxe.inf
INF QcomPkg/Drivers/MeasureBootDxe/MeasureBootDxe.inf
INF MdeModulePkg/Universal/SmbiosMeasurementDxe/SmbiosMeasurementDxe.inf
INF Sc8380xpFamilyPkg/ParallelFvSupportDxe/ParallelFvSupportDxe.inf

FILE FREEFORM = 4BA47E84-4EF7-11E8-AD64-832B78EEA48D {
    SECTION UI = "MsPlatformPanel_lcd.xml"
    SECTION RAW = RawFiles/MsPlatformPanel_lcd.xml
}


FILE FREEFORM = 1B198381-97F4-4CC2-BB50-154D4A748D5A {
    SECTION UI = "MsPlatformPanel_oled.xml"
    SECTION RAW = RawFiles/MsPlatformPanel_oled.xml
}


FILE FREEFORM = A1E235DE-E825-4591-9623-C43175811826 {
    SECTION UI = "SecParti.cfg"
    SECTION RAW = RawFiles/SecParti.cfg
}


FILE FREEFORM = 21E9BDD9-6C3F-4F10-84A5-BBEC322741F1 {
    SECTION UI = "uefipil.cfg"
    SECTION RAW = RawFiles/uefipil.cfg
}


FILE FREEFORM = 45FE4B7C-150C-45DA-A021-4BEB2048EC6F {
    SECTION UI = "QcomChargerCfg.cfg"
    SECTION RAW = RawFiles/QcomChargerCfg.cfg
}

INF MsSurfaceCorePkg/Universal/MsBootPolicy/MsBootPolicy.inf
INF MsSurfaceCorePkg/Application/SurfaceFrontPage/SurfaceFrontPage.inf
INF MsSurfaceCorePkg/Application/BootMenu/BootMenu.inf
INF MsSurfaceCorePkg/Application/SetTimeMenu/SetTimeMenu.inf
INF QcomPkg/Drivers/EmbeddedMonotonicCounter/EmbeddedMonotonicCounter.inf
INF QcomPkg/Drivers/AdapterInformationDxe/AdapterInformationDxe.inf
INF QcomPkg/Drivers/MorPpiDxe/MorPpiDxe.inf
INF QcomPkg/Drivers/RecoveryDxe/RecoveryDxe.inf
INF MdeModulePkg/Universal/Acpi/FirmwarePerformanceDataTableDxe/FirmwarePerformanceDxe.inf
INF MdeModulePkg/Universal/Acpi/BootGraphicsResourceTableDxe/BootGraphicsResourceTableDxe.inf
INF SecurityPkg/Tcg/Opal/OpalPassword/OpalPasswordDxe.inf
INF MsSamSupportPkg/UspHidDxe/UspHidDxe.inf
INF MsSurfaceCorePkg/MsBoardIdInfo/MsBoardIdInfoDxe.inf
INF MdeModulePkg/Universal/MemoryTest/NullMemoryTestDxe/NullMemoryTestDxe.inf
INF MsSurfaceCorePkg/MfciManufacturingModeDxe/MfciManufacturingMode.inf
INF MfciPkg/MfciDxe/MfciDxe.inf
INF Sc8380xpFamilyPkg/QcMfgModeDxe/QcMfgModeDxe.inf
INF MsSurfaceQcPkg/DppInitDxe/DppInitDxe.inf
INF MsSurfaceCorePkg/MsManufacturingModeReclaimDxe/MsManufacturingModeReclaimDxe.inf
INF MsWheaPkg/HwErrBert/HwErrBert.inf
INF MsSamSupportPkg/SamCapabilitiesDxe/SamCapabilitiesDxe.inf
INF MsSamSupportPkg/PowerSupply/PowerSupply.inf
INF MsSamSupportPkg/SamRealTimeClockDxe/SamRealTimeClockDxe.inf
INF MsSamSupportPkg/SamUefiDoneDxe/SamUefiDoneDxe.inf
INF HidPkg/HidKeyboardDxe/HidKeyboardDxe.inf
INF HidPkg/HidMouseAbsolutePointerDxe/HidMouseAbsolutePointerDxe.inf
INF MsSurfaceCorePkg/SurfaceHidSpiDeviceDxe/SurfaceHidSpiDeviceDxe.inf
INF MsSurfaceCorePkg/HidSpiDeviceControllerInitDxe/HidSpiDeviceControllerInitDxe.inf
INF MsSurfaceCorePkg/MsSmbiosDxe/MsSmbiosDxe.inf
INF MsCorePkg/MacAddressEmulationDxe/MacAddressEmulationDxe.inf
INF Sc8380xpFamilyPkg/TdmStorageAccessDxe/TdmStorageAccessDxe.inf
INF MsSurfaceCorePkg/MsCalibrationServicingDxeV2/MsCalibrationServicingDxe.inf
INF MsSurfaceCorePkg/MsPlatformDisplayInfoDxe/MsPlatformDisplayInfoDxe.inf
INF MsSurfaceCorePkg/MsPlatformDisplayInfoDxe/9BFA1EE3-98E1-4230-99EE-08FFCCA482A9.inf
INF MsSurfaceCorePkg/MsTouchUnlockDxe/MsTouchUnlockDxe.inf
INF MsGraphicsPkg/MsEarlyGraphics/Dxe/MsEarlyGraphics.inf
INF Sc8380xpFamilyPkg/DisplayHandoffDxe/DisplayHandoffDxe.inf
INF MsGraphicsPkg/GopOverrideDxe/GopOverrideDxe.inf
INF MsSurfaceQcPkg/Override/MsGraphicsPkg/RenderingEngineDxe/RenderingEngineDxe.inf
INF MsGraphicsPkg/SimpleWindowManagerDxe/SimpleWindowManagerDxe.inf
INF MsGraphicsPkg/OnScreenKeyboardDxe/OnScreenKeyboardDxe.inf
INF MsGraphicsPkg/DisplayEngineDxe/DisplayEngineDxe.inf
INF MdeModulePkg/Universal/SetupBrowserDxe/SetupBrowserDxe.inf
INF MsCorePkg/MuCryptoDxe/MuCryptoDxe.inf
INF MsCorePkg/CheckHardwareConnected/CheckHardwareConnected.inf
INF MdeModulePkg/Universal/RegularExpressionDxe/RegularExpressionDxe.inf
INF MsSurfaceCorePkg/MuBuiltInVarPolicyInstallerDxe/CBB497B8-7F8D-48E6-A535-09B71955E669.inf
INF AdvLoggerPkg/AdvancedFileLogger/AdvancedFileLogger.inf
INF DfciPkg/SettingsManager/SettingsManagerDxe.inf
INF SemmPkg/SemmManager/SemmManager.inf
INF DfciPkg/DfciManager/DfciManager.inf
INF DfciPkg/IdentityAndAuthManager/IdentityAndAuthManagerDxe.inf
INF DfciPkg/Application/DfciMenu/DfciMenu.inf
INF SemmPkg/Application/SemmMenu/SemmMenu.inf
INF MsSurfaceCorePkg/MsSkuDifferentiation/Dxe/MsSkuDiffDxe.inf
INF MsSurfaceCorePkg/MsProtectionPolicyDxe/MsProtectionPolicyDxe.inf
INF DenaliPkg/TdmDependencyDxe/TdmDependencyDxe.inf
INF MdeModulePkg/Universal/EsrtFmpDxe/EsrtFmpDxe.inf
INF FmpDevicePkg/FmpDxe/A5F91090-3EFC-4BC2-BE0A-28C56DD0BA73.inf
INF FmpDevicePkg/FmpDxe/A7F828C6-4925-459E-94FD-55615C440162.inf
INF FmpDevicePkg/FmpDxe/C2A75329-58E2-4910-9A05-1A5818EA6777.inf
INF FmpDevicePkg/FmpDxe/B0FF22E2-4AEA-4725-A6E5-5317FB8FD39C.inf
INF FmpDevicePkg/FmpDxe/29B5DCCA-8EBE-43ED-9D1C-BBF7FC430DD7.inf
INF FmpDevicePkg/FmpDxe/83FCFB88-D008-4AF7-B2B1-BF86F6E3DE8A.inf
INF FmpDevicePkg/FmpDxe/1DA8F1C2-81CC-43BC-B85A-BA3A51CDBBA9.inf
INF FmpDevicePkg/FmpDxe/759A4BF6-721D-4793-A4A2-F85769C3B570.inf
INF FmpDevicePkg/FmpDxe/C3DAD8A7-F443-4A0F-A53C-E8DAFC0E09AB.inf
INF FmpDevicePkg/FmpDxe/77B108CA-99B7-4BAD-A849-B39342D6721F.inf
INF MsSurfaceQcPkg/ColorbarsDxe/ColorbarsDxe.inf
INF MsSurfaceCorePkg/MsReservedMemoryOpregionDxe/MsReservedMemoryOpregionDxe.inf
INF MsSurfaceCorePkg/SurfaceOA3Dxe/SurfaceOA3.inf
INF MsSurfaceCorePkg/ResetReason/ResetReason.inf
INF QcomPkg/Application/QcomChargerApp/QcomChargerAppWP.inf
INF Sc8380xpFamilyPkg/SmbiosUpdatesDxe/SmbiosUpdatesDxe.inf
INF Sc8380xpFamilyPkg/BootButtonsDxe/BootButtons.inf
INF MsSurfaceCorePkg/MsTpmConfigurationDxe/MsTpmConfigurationDxe.inf
INF MsSurfaceQcPkg/MsAbtConfig/MsAbtConfig.inf

FILE FREEFORM = 7BB28B99-61BB-11D5-9A5D-0090273FC14D {
    SECTION RAW = RawFiles/Logo
    SECTION UI = "Logo"
}


FILE FREEFORM = D2AF039E-9F1F-4616-97AF-BE4509A365EA {
    SECTION RAW = RawFiles/Low_Battery
    SECTION UI = "Low Battery"
}


FILE FREEFORM = 7C3A8851-A6D2-445B-A53B-155F867AB4DA {
    SECTION RAW = RawFiles/Too_Hot
    SECTION UI = "Too Hot"
}


FILE FREEFORM = 4FFEE6D5-B396-40F9-9246-7A8E4A821720 {
    SECTION RAW = RawFiles/FirmwareSettingsIndicator
    SECTION UI = "FirmwareSettingsIndicator"
}


FILE FREEFORM = F1E7A352-46AE-4912-92AF-36AB51781D8E {
    SECTION RAW = RawFiles/BootFailIndicator
    SECTION UI = "BootFailIndicator"
}


FILE FREEFORM = AE2D011C-4128-4960-A536-B424CCC3D1EA {
    SECTION RAW = RawFiles/VolumeUpIndicator
    SECTION UI = "VolumeUpIndicator"
}

INF MsSurfaceQcPkg/Override/MsSurfaceCorePkg/SurfaceTpm/SurfaceTpm.inf
INF MsSurfaceCorePkg/Override/MdeModulePkg/Universal/BootManagerPolicyDxe/BootManagerPolicyDxe.inf
INF NetworkPkg/DpcDxe/DpcDxe.inf
INF NetworkPkg/SnpDxe/SnpDxe.inf
INF NetworkPkg/VlanConfigDxe/VlanConfigDxe.inf
INF NetworkPkg/MnpDxe/MnpDxe.inf
INF NetworkPkg/ArpDxe/ArpDxe.inf
INF NetworkPkg/Dhcp4Dxe/Dhcp4Dxe.inf
INF NetworkPkg/Ip4Dxe/Ip4Dxe.inf
INF NetworkPkg/Udp4Dxe/Udp4Dxe.inf
INF NetworkPkg/Mtftp4Dxe/Mtftp4Dxe.inf
INF NetworkPkg/Dhcp6Dxe/Dhcp6Dxe.inf
INF NetworkPkg/Ip6Dxe/Ip6Dxe.inf
INF NetworkPkg/Udp6Dxe/Udp6Dxe.inf
INF NetworkPkg/Mtftp6Dxe/Mtftp6Dxe.inf
INF NetworkPkg/TcpDxe/TcpDxe.inf
INF NetworkPkg/UefiPxeBcDxe/UefiPxeBcDxe.inf
INF NetworkPkg/DnsDxe/DnsDxe.inf
INF NetworkPkg/HttpDxe/HttpDxe.inf
INF NetworkPkg/HttpUtilitiesDxe/HttpUtilitiesDxe.inf
INF NetworkPkg/TlsDxe/TlsDxe.inf
INF QcomPkg/QcomWlanPkg/QcaWifiDxe/QcaWifiDxe.inf
INF Ms_Network/Ms_Network.inf
INF QcomPkg/Drivers/CrashDumpDxe/CrashDumpDxe.inf
INF MsSurfaceCorePkg/MsSSDEntryLoggerDxe/MsSSDEntryLoggerDxe.inf
INF MsSurfaceCorePkg/VariableDefaults/VariableDefaultsDxe.inf
INF MsSurfaceCorePkg/ScpcWindowsVariableDxe/ScpcWindowsVariableDxe.inf
INF DenaliPkg/PlatformInitDxe/PlatformInitDxe.inf
INF DenaliPkg/DeviceTpmConfigDxe/DeviceTpmConfigDxe.inf
INF MsSurfaceCorePkg/MsUsbUndiConfigurationDxe/MsUsbUndiConfigurationDxe.inf
INF MsSurfaceQcPkg/MsRunPrebootApp/MsRunPrebootAppDxe.inf

FILE FREEFORM = 56FB654D-2579-47A3-8120-854449FE178E {
    SECTION RAW = RawFiles/SsdtSurfAcpi
    SECTION UI = "SsdtSurfAcpi"
}


FILE FREEFORM = 60055B70-03CF-482B-AAF9-B6AA2F0B0171 {
    SECTION RAW = RawFiles/DenaliManf
    SECTION UI = "DenaliManf"
}

INF Sc8380xpFamilyPkg/Acpi/AcpiTables/SsdtSurf/SsdtSurfDxe.inf
INF MsSurfaceCorePkg/SsdtManf/SsdtManfDxe.inf
INF HidPkg/UsbHidDxe/UsbHidDxe.inf
INF UefiHidDxeV2/UefiHidDxeV2.inf
